### ISSUE TITLE
How to config shared dep path matching with vite alias

### ISSUE THREAD

**Issue by yuanlin1995** [module-federation/vite#17]
vue alias config to vue.esm.js, but shared vue path is vue.runtime.esm.js;

**Comment by gioboa** [comment]
Hi, can you explain the problem in a different way please? I can't understand how can I help you

**Comment by levrik** [comment]
Hi @gioboa. I think I'm hitting the same issue here. Let me explain a bit in more detail.
Vue by default ships without the template compiler and just the runtime. In some scenarios you need the template compiler to be shipped in the bundle. For this you have to alias `vue` to `vue/dist/vue.esm-bundler.js` (it resolves to `vue/dist/vue.runtime.esm-bundler.js` by default). If you now put module federation into play, this aliased bundle must be shared instead of the default bundle.

I originally had the alias configured like this which just silently did not work.

```js
{ find: 'vue', replacement: fileURLToPath(new URL('./node_modules/vue/dist/vue.esm-bundler.js', import.meta.url)) }
```

After changing it to this

```js
{ find: 'vue', replacement: 'vue/dist/vue.esm-bundler.js' }
```

I'm now getting a warning:

```
[Module Federation] Detected alias conflicts with shared modules:
[Module Federation] Shared module "vue" is aliased by "vue" to "vue/dist/vue.esm-bundler.js"
[Module Federation] This may cause runtime errors as the shared module will bypass Module Federation's sharing mechanism.
```

To also give you an example why you would want to switch to the compiler-bundle: We have server-side rendered HTML templates through a legacy Perl codebase. So basically the server outputs something like `<div id="vue-mount"><some-vue-component prop="value" /></div>`. Vue then mounts into `vue-mount` element and interprets its contents as a template which it has to compile in-browser. This is necessary to be able to pass props from server-side into the Vue root component.

This alias is documented here:

https://vuejs.org/guide/scaling-up/tooling.html#note-on-in-browser-template-compilation

> Our default tooling setups use the runtime-only build since all templates in SFCs are pre-compiled. If, for some reason, you need in-browser template compilation even with a build step, you can do so by configuring the build tool to alias `vue` to `vue/dist/vue.esm-bundler.js` instead.

**Comment by gioboa** [comment]
I see, that’s a really old issue. Let me check.

**Comment by levrik** [comment]
@gioboa I just stumbled across the `import` option inside `shared`. I tried the following configuration:

```js
shared: {
    'vue': {
        singleton: true,
        import: 'vue/dist/vue.esm-bundler.js'
    }
}
```

But at runtime I'm getting `Uncaught (in promise) SyntaxError: The requested module '/@id/__x00__virtual:mf:__mfe_internal__ov_mf_2_im__loadShare__vue__loadShare__.js' does not provide an export named 'Comment' (at veaury.js?v=0d3d3ba7:4:10)`. Maybe I'm misunderstanding this option or did I find a bug?

**Comment by gioboa** [comment]
Do you have a basic repo to clone and reproduce the issue?

**Comment by levrik** [comment]
@gioboa Can you confirm that the `import` option should allow sharing the alternative bundle? If yes, then I'll open a separate issue with a repro tomorrow. I don't have time for this today anymore.

**Comment by gioboa** [comment]
Yes, `import` should be the right option for this use case. Let's continue the conversation in a new issue. please include a basic repo to reproduce it.

**Comment by levrik** [comment]
@gioboa Opened the issue over here: https://github.com/module-federation/vite/issues/896
Repro is linked
