### ISSUE TITLE
The project doesn't running with deps in "DEPENDECIES"

### ISSUE THREAD

**Issue by pedrocandidozup** [module-federation/vite#24]
I look for the projects @gioboa is providing in the github, but all the projects you put all dependecies in "devDependecies" for the project work, e.g: 

https://github.com/gioboa/react-microfrontends-spotify/blob/main/host/package.json

Is the same for me in the projects, when I putting some deps in "dependencies" is shown the error
![image](https://github.com/module-federation/vite/assets/153231511/dc257502-91f7-46f4-b256-357e6d6c8bf6)

and If I stay "react" in "dependecies" the error is shown 
**The entry point "react" cannot be marked as externa**

**Comment by sedx** [comment]
Hi! For solving `The entry point "react" cannot be marked as external` see my answer in this issue  https://github.com/module-federation/vite/issues/16#issuecomment-2072213372

For suppress pre-transform error, try to set `server.preTransformRequests`  to `false` in vite config. Looks like we don't need deps pre-transformation because it's work of adapter.

**Comment by pedrocandidozup** [comment]
@sedx yes, after that, I tried to removed "react" at vite.config, but I think it not the best solutions.. 

I will try use "server.preTransformRequests"

**Comment by gioboa** [comment]
We are working on a new version that will definitely solves this. @ScriptedAlchemy did a big step forward, he did the official esbuild adapter and the runtime loaders too.

**Comment by gioboa** [comment]
We are working on a new version of this package in [this PR](https://github.com/module-federation/vite/pull/34) 
I'm closing this issue, if you want, you can try the new version and give us feedback. Thanks.
