### ISSUE TITLE
v1.0.0: Question: re `.__mf__win`

### ISSUE THREAD

**Issue by husayt** [module-federation/vite#74]
@zhangHongEn I see new folder `.__mf__win` created when running latest demo. What is it for?

**Comment by zhangHongEn** [comment]
The syntax `shared: "react/"` can only know which sub-paths are imported during the build execution process, and it is unknown at the beginning.
I need to trigger the vite pre-build again after the build is completed, which is achieved by modifying the .__mf__win/localSharedImportMap.js file
Due to this [bug](https://github.com/vitejs/vite/issues/8619), I had to create it outside of node_modules on Windows

**Comment by husayt** [comment]
@gioboa thank you, I forgot to close

@zhangHongEn thanks for clarification
